language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: "3.4.7"

script:
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install hxjava
  - haxelib install hxnodejs
  - haxelib install format
  - haxelib install thx.semver
  - haxelib dev om.core .
  - haxe doc.hxml
  #- haxe --cwd test build.hxml
