language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.2"
  - development

matrix:
  allow_failures:
    - haxe: development

script:
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install hxjava
  - haxelib install hxnodejs
  - haxelib install format
  - haxelib install thx.semver
  - haxelib git om.core https://github.com/tong/om.core
  - haxe doc.hxml
  #- haxe --cwd test build.hxml
