language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - development

addons:
  apt:
    packages:
      - mono-devel
      - mono-mcs
      - python3
      - gcc-multilib
      - g++-multilib

matrix:
  allow_failures:
    - haxe: "3.4.7"

install:
  - haxelib install electron
  - haxelib install format
  - haxelib install hashlink
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install hxjava
  - haxelib install hxnodejs
  - haxelib git utest https://github.com/tong/utest.git
  - haxelib git om.test https://github.com/omlib/om.test.git
  - haxelib dev om.core .

script:
  - haxe doc.hxml
  - haxe --cwd test build.hxml
