name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup haxe
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install haxe -y
          mkdir ~/haxelib && haxelib setup ~/haxelib
          haxelib dev om.core .
          haxelib install hxcpp
          haxelib install hxcs
          haxelib install hxjava
          haxelib install hxnodejs
          haxelib install format
          haxelib install utest
      - name: Run unit tests
        run: haxe test.hxml
      - name: Build haxedocs
        run: haxe doc.hxml
