name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Setup haxe
        run: |
          haxelib dev om.core .
          haxelib install hxcpp
          haxelib install hxjava
          haxelib install hxnodejs
          haxelib install format
          haxelib install utest
      - name: Run unit tests
        run: haxe test.hxml
      - name: Build haxedocs
        run: haxe doc.hxml
