name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        haxe:
          - 4.3.7
          - latest
        include:
          - haxe: latest
            allow-failure: true
    steps:
      - uses: actions/checkout@v4
      - name: Install haxe ${{ matrix.haxe }}
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ matrix.haxe }}
      - name: Setup haxe
        run: |
          haxelib dev om.core .
          haxelib install hxcpp
          haxelib install hxjava
          haxelib install hxnodejs
          haxelib install format
          haxelib install utest
      - name: Run unit tests
        run: haxe test.hxml
        continue-on-error: ${{ matrix.allow-failure || false }}
      - name: Build haxedocs
        run: haxe doc.hxml
        continue-on-error: ${{ matrix.allow-failure || false }}
